# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# Installation packages for the work in this repo 

# Setting up a task template 

# - name: Rust Install
#   init: >
#     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#   command: |
#     source $HOME/.cargo/env
#     rustup component add rustfmt

tasks:

# Rust install 
- name: Rust Install
  init: >
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    gp sync-done rustinstall
  command: |
    source $HOME/.cargo/env
    rustup component add rustfmt
  openMode: tab-after

# Install Solana 
- name: Solana Install
  init: >
   gp sync-await rustinstall
   sh -c "$(curl -sSfL https://release.solana.com/v1.8.0/install)" && 
   export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH" &&
   source ~/.bashrc &&
   echo $PATH | grep solana &&
  command:  solana
  openMode: tab-after

# Install Solana 
- name: Mocha Global install 
  init: >
    gp sync-await rustinstall
    npm install -g mocha
  openMode: tab-after

# Install Anchor
- name: Anchor Install 
  init: >
    gp sync-await rustinstall
    npm i -g @project-serum/anchor-cli
  command: anchor 
  openMode: tab-after

# Add path when opening a new terminal
# You need to add these to bashrc everytime you open a terminal, since gitpod doesnt give permissions to edit 
# /etc/environment & /etc/profile
# - name: Add Solana Path 
#   init: |
#     gp sync-await rustinstall
#   command: |
#     echo "Run following commands when opening a new terminal" &&
#     echo "export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH" && 
#     echo "source ~/.bashrc" 
#   openMode: tab-after


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
