#!/bin/bash
# Script written from setting the solana path, since at he time of maing this unsure how to set global path 
# variable in gitpod 
# Command to execute here is 
# $ . ./SetSolanaPath 
./

clear

# Setting the solana path 

echo -e "------------------------------------------------------"
echo -e "This will set solana path and show the path of solana "
echo -e "------------------------------------------------------"
echo -e "The following commands will be run"
echo -e "------------------------------------------------------"
echo -e " "
echo -e "source ~/.bashrc - For sourcing the bash "
echo -e "e c h o $ PATH | grep solana - For displaying the path"
echo -e "solana --version - Checking solana version"
echo -e ""


read -n 1 -s -r -p "Press any key to continue"

export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"
source ~/.bashrc
echo $PATH | grep solana
solana --version

# Setting the solana config to devnet 
echo -e "------------------------------------------------------"
echo -e "Now solana will be set to devnet "
echo -e " solana config -set devnet"
echo -e "------------------------------------------------------"

read -n 1 -s -r -p "Press any key to continue"
solana config set -u devnet 

# Once above is done the next steo wil be to setup the accounts the next step is to
# get a new keypair 

echo -e "------------------------------------------------------"
echo -e "Generate Solana Key - Force flag being used will addd new keys"
echo -e " solana-keygen new -f"
echo -e " solana address"
echo -e "------------------------------------------------------"

read -n 1 -s -r -p "Press any key to continue"
solana-keygen new -f
solana address 

# After than lets airdrop 1 sol to the account so that account address will be visible 
echo -e "------------------------------------------------------"
echo -e "Airdrop 1 SOL - Devenet SOL needs to be done in increments"
echo -e " solana airdrop 2"
echo -e "------------------------------------------------------"

read -n 1 -s -r -p "Press any key to continue"
solana airdrop 2 

# Now to see the account contents 
echo -e "------------------------------------------------------"
echo -e "Airdrop 1 SOL - Devenet SOL needs to be done in increments"
echo -e " solana airdrop 2"
echo -e "------------------------------------------------------"
